(deftheme Witchmacs
  "Created 2019-05-18.")

(custom-theme-set-variables
 'Witchmacs
 '(ansi-color-names-vector ["#262626" "#FF6666" "#A6E22E" "#FFFF66" "#6666FF" "#FD5FF0" "#99CCFF" "#F1EFEE"]))

(custom-theme-set-faces
 'Witchmacs
 '(font-lock-builtin-face ((t (:foreground "#FF6666" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((t (:foreground "#E6DB74"))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22E"))))
 '(font-lock-keyword-face ((t (:foreground "#FF6666" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#FF6666"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((t (:foreground "#99CCFF" :slant normal))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(button ((t (:underline t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#49483E")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:inherit highlight :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit highlight :background "#3E3E3E"))))
 '(region ((((class color) (min-colors 257)) (:inherit highlight :background "#49483E")) (((class color) (min-colors 89)) (:inherit highlight :background "#474747"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:inherit region :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit region :background "#3E3E3E"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((t (:background "#E6DB74" :foreground "#262626" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#262626" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#262626" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#262626")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#AE81FF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((t (:foreground "#A6E22E"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((t (:foreground "#FF6666"))))
 '(trailing-whitespace ((t (:background "#FF6666"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#64645E")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#262626")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((t (:foreground "#99CCFF"))))
 '(mode-line-buffer-id ((t (:foreground "#E6DB74" :weight bold))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#49483E" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#1B1E1C" :box (:line-width 1 :color "#474747" :style unspecified)))))
 '(powerline-active1 ((((class color) (min-colors 257)) (:background "#35331D")) (((class color) (min-colors 89)) (:background "#333333"))))
 '(powerline-active2 ((((class color) (min-colors 257)) (:background "#262626")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#262626" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#3D3D3D" :style unspecified)))))
 '(powerline-inactive1 ((((class color) (min-colors 257)) (:background "#35331D")) (((class color) (min-colors 89)) (:background "#333333"))))
 '(powerline-inactive2 ((((class color) (min-colors 257)) (:background "#262626")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(header-line ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#49483E" :box (:color "#64645E" :line-width 1 :style unspecified))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#474747" :box (:color "#3D3D3D" :line-width 1 :style unspecified)))))
 '(diary ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(isearch ((((class color) (min-colors 257)) (:inherit region :foreground "#262626" :background "#E6DB74")) (((class color) (min-colors 89)) (:inherit region :foreground "#1B1E1C" :background "#CDC673"))))
 '(isearch-fail ((t (:background "#ff6666" :foreground "#262626" :weight bold))))
 '(company-tooltip ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-tooltip-selection ((t (:background "#99CCFF" :foreground "#262626"))))
 '(company-tooltip-mouse ((t (:background "#99CCFF" :foreground "#262626"))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#64645E")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#75715E")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(company-tooltip-annotation ((t (:background "#3C3D37" :foreground "#E6DB74"))))
 '(company-template-field ((t (:background "#3C3D37" :foreground "#99CCFF"))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493" :height 1.2))))
 '(custom-state ((t (:foreground "#A6E22E"))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#FA518D" :inherit italic)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FF5F87" :inherit italic))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#BBEF53" :inherit italic)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#AFD700" :inherit italic))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#E6DB74") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#F92672") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#F92672" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold :underline t))))
 '(info-header-xref ((((class color) (min-colors 257)) (:foreground "#A6E22E" :inherit bold :underline t)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold :underline t))))
 '(info-node ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 257)) (:height 1.3)) (((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-2 ((((class color) (min-colors 257)) (:height 1.2)) (((class color) (min-colors 89)) (:height 1.2))))
 '(info-title-3 ((((class color) (min-colors 257)) (:height 1.15)) (((class color) (min-colors 89)) (:height 1.15))))
 '(info-title-4 ((((class color) (min-colors 257)) (:height 1.1)) (((class color) (min-colors 89)) (:height 1.1))))
 '(linum ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#262626" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :inherit default :underline nil))))
 '(line-number ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#262626" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :inherit default :underline nil))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#262626" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inherit default :underline nil))))
 '(show-paren-match ((t (:background "#75715E" :foreground "#99CCFF" :inverse-video t :weight normal))))
 '(show-paren-mismatch ((t (:background "#262626" :foreground "#FF6666" :inverse-video t :weight normal))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#FFFACE" :foreground "#262626" :inherit default))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#262626")) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#E6DB74"))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#99CCFF" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#262626" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(which-key-key-face ((t (:foreground "#E6DB74" :weight bold))))
 '(which-key-separator-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(which-key-note-face ((t (:foreground "#75715E"))))
 '(which-key-command-description-face ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(which-key-local-map-description-face ((((class color) (min-colors 257)) (:foreground "#FFFACE")) (((class color) (min-colors 89)) (:foreground "#878700"))))
 '(which-key-group-description-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(dashboard-text-banner ((t (:foreground "#E6DB74"))))
 '(dashboard-heading ((t (:foreground "#E6DB74"))))
 '(spaceline-highlight-face ((t (:background "#412094" :foreground "#F8F8F2"))))
 '(link ((t (:foreground "#99CCFF" :underline t))))
 '(company-preview-common ((t (:foreground "#99CCFF" :underline t))))
 '(company-tooltip-common-selection ((t (:background "#99CCFF" :foreground "#262626" :underline "#99CCFF"))))
 '(ido-subdir ((t (:foreground "#FF6666"))))
 '(ido-only-match ((t (:foreground "#A6E22E"))))
 '(ido-indicator ((t (:background "#FF6666" :foreground "#E6DB74" :width condensed))))
 '(hl-line ((t (:background "#202020"))))
 '(default ((t (:background "#262626" :foreground "#F8F8F2"))))
 '(term-color-black ((t (:background "#1A1A1A" :foreground "#1A1A1A"))))
 '(term-color-blue ((t (:background "#6666FF" :foreground "#6666FF"))))
 '(term-color-cyan ((t (:background "#99CCFF" :foreground "#99CCFF"))))
 '(term-color-green ((t (:background "#A6E22E" :foreground "#A6E22E"))))
 '(term-color-magenta ((t (:background "#FF66FF" :foreground "#FF66FF"))))
 '(term-color-red ((t (:background "#FF6666" :foreground "#FF6666"))))
 '(term-color-white ((t (:background "#F1EFEE" :foreground "#F1EFEE"))))
 '(term-color-yellow ((t (:background "#FFFF66" :foreground "#FFFF66")))))

(provide-theme 'Witchmacs)
